language: csharp
solution: MonoRPG.sln
mono:
  - latest
install:
  - wget http://www.monogame.net/releases/v3.5.1/monogame-sdk.run -O /tmp/monogame-sdk.run && chmod +x /tmp/monogame-sdk.run && /tmp/monogame-sdk.run --noexec
  - nuget restore MonoRPG.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild MonoRPG.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/Test.csproj
