language: csharp
solution: ProtoRpg.sln
install:
  - nuget restore ProtoRpg.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ProtoRpg.sln
