language: csharp
solution: ProtoRpg.sln
mono:
  - latest
install:
  - nuget install MonoGame.Framework.Linux
  - nuget restore ProtoRpg.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild MonoRPG.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/Test.csproj
