language: csharp
solution: ProtoRpg.sln
install:
  - nuget restore ProtoRpg.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release ProtoRpg.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/bin/Release/Test.dll
