language: csharp
solution: MonoRPG.sln
mono:
  - latest
install:
  - wget http://www.monogame.net/releases/v3.5/monogame-sdk.deb -O /tmp/monogame-sdk.deb && sudo dpkg -i /tmp/monogame-sdk.deb
  - nuget restore MonoRPG.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild MonoRPG.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Test/Test.csproj
