
// This file has been generated by the GUI designer. Do not modify.
namespace Editor
{
	public partial class DatabaseManagerWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action addTilesetAction;
		
		private global::Gtk.Action removeTilesetAction;
		
		private global::Gtk.RadioAction PassageAction;
		
		private global::Gtk.RadioAction priorityAction;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.HPaned hpaned1;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.NodeView tilesetsNodeView;
		
		private global::Gtk.Toolbar tilesetsToolbar;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Frame frame2;
		
		private global::Gtk.Alignment GtkAlignment2;
		
		private global::Gtk.Table table1;
		
		private global::Gtk.Button button13;
		
		private global::Gtk.Entry entry2;
		
		private global::Gtk.Entry entry3;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Label label3;
		
		private global::Gtk.Label GtkLabel3;
		
		private global::Gtk.ScrolledWindow scrolledwindow1;
		
		private global::Editor.TilesetEditorWidget tileseteditorwidget3;
		
		private global::Gtk.Toolbar toolbar1;
		
		private global::Gtk.Label tilesetsPage;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Editor.DatabaseManagerWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.addTilesetAction = new global::Gtk.Action ("addTilesetAction", global::Mono.Unix.Catalog.GetString ("Add"), null, "gtk-add");
			this.addTilesetAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Add");
			w1.Add (this.addTilesetAction, null);
			this.removeTilesetAction = new global::Gtk.Action ("removeTilesetAction", global::Mono.Unix.Catalog.GetString ("Remove"), null, "gtk-remove");
			this.removeTilesetAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Remove");
			w1.Add (this.removeTilesetAction, null);
			this.PassageAction = new global::Gtk.RadioAction ("PassageAction", global::Mono.Unix.Catalog.GetString ("Passage"), null, null, 0);
			this.PassageAction.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.PassageAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Passage");
			w1.Add (this.PassageAction, null);
			this.priorityAction = new global::Gtk.RadioAction ("priorityAction", global::Mono.Unix.Catalog.GetString ("Priority"), null, null, 0);
			this.priorityAction.Group = this.PassageAction.Group;
			this.priorityAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Priority");
			w1.Add (this.priorityAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Editor.DatabaseManagerWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("DatabaseManager");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			this.DefaultWidth = 900;
			this.DefaultHeight = 600;
			this.DestroyWithParent = true;
			// Internal child Editor.DatabaseManagerWindow.VBox
			global::Gtk.VBox w2 = this.VBox;
			w2.Name = "dialog1_VBox";
			w2.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 0;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.hpaned1 = new global::Gtk.HPaned ();
			this.hpaned1.CanFocus = true;
			this.hpaned1.Name = "hpaned1";
			this.hpaned1.Position = 223;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tilesetsNodeView = new global::Gtk.NodeView ();
			this.tilesetsNodeView.CanFocus = true;
			this.tilesetsNodeView.Name = "tilesetsNodeView";
			this.GtkScrolledWindow.Add (this.tilesetsNodeView);
			this.vbox2.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.GtkScrolledWindow]));
			w4.Position = 1;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='tilesetsToolbar'><toolitem name='addTilesetAction' action='addTilesetAction'/><toolitem name='removeTilesetAction' action='removeTilesetAction'/></toolbar></ui>");
			this.tilesetsToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/tilesetsToolbar")));
			this.tilesetsToolbar.Name = "tilesetsToolbar";
			this.tilesetsToolbar.ShowArrow = false;
			this.tilesetsToolbar.ToolbarStyle = ((global::Gtk.ToolbarStyle)(0));
			this.tilesetsToolbar.IconSize = ((global::Gtk.IconSize)(1));
			this.vbox2.Add (this.tilesetsToolbar);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.tilesetsToolbar]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.hpaned1.Add (this.vbox2);
			global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vbox2]));
			w6.Resize = false;
			// Container child hpaned1.Gtk.Paned+PanedChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.frame2 = new global::Gtk.Frame ();
			this.frame2.Name = "frame2";
			this.frame2.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child frame2.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(3)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.button13 = new global::Gtk.Button ();
			this.button13.CanFocus = true;
			this.button13.Name = "button13";
			this.button13.UseUnderline = true;
			this.button13.Label = global::Mono.Unix.Catalog.GetString ("...");
			this.table1.Add (this.button13);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.button13]));
			w7.TopAttach = ((uint)(1));
			w7.BottomAttach = ((uint)(2));
			w7.LeftAttach = ((uint)(2));
			w7.RightAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry2 = new global::Gtk.Entry ();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '●';
			this.table1.Add (this.entry2);
			global::Gtk.Table.TableChild w8 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry2]));
			w8.LeftAttach = ((uint)(1));
			w8.RightAttach = ((uint)(2));
			w8.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.entry3 = new global::Gtk.Entry ();
			this.entry3.CanFocus = true;
			this.entry3.Name = "entry3";
			this.entry3.IsEditable = true;
			this.entry3.InvisibleChar = '●';
			this.table1.Add (this.entry3);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.entry3]));
			w9.TopAttach = ((uint)(1));
			w9.BottomAttach = ((uint)(2));
			w9.LeftAttach = ((uint)(1));
			w9.RightAttach = ((uint)(2));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Name");
			this.table1.Add (this.label2);
			global::Gtk.Table.TableChild w10 = ((global::Gtk.Table.TableChild)(this.table1 [this.label2]));
			w10.XOptions = ((global::Gtk.AttachOptions)(4));
			w10.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Graphics");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			this.GtkAlignment2.Add (this.table1);
			this.frame2.Add (this.GtkAlignment2);
			this.GtkLabel3 = new global::Gtk.Label ();
			this.GtkLabel3.Name = "GtkLabel3";
			this.GtkLabel3.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Tileset settings</b>");
			this.GtkLabel3.UseMarkup = true;
			this.frame2.LabelWidget = this.GtkLabel3;
			this.hbox1.Add (this.frame2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.frame2]));
			w14.Position = 0;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w15 = new global::Gtk.Viewport ();
			w15.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.tileseteditorwidget3 = new global::Editor.TilesetEditorWidget ();
			this.tileseteditorwidget3.Events = ((global::Gdk.EventMask)(256));
			this.tileseteditorwidget3.Name = "tileseteditorwidget3";
			w15.Add (this.tileseteditorwidget3);
			this.scrolledwindow1.Add (w15);
			this.hbox1.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.scrolledwindow1]));
			w18.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='PassageAction' action='PassageAction'/><toolitem name='priorityAction' action='priorityAction'/></toolbar></ui>");
			this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
			this.toolbar1.Name = "toolbar1";
			this.toolbar1.Orientation = ((global::Gtk.Orientation)(1));
			this.toolbar1.ShowArrow = false;
			this.toolbar1.ToolbarStyle = ((global::Gtk.ToolbarStyle)(1));
			this.hbox1.Add (this.toolbar1);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.toolbar1]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.hpaned1.Add (this.hbox1);
			this.notebook1.Add (this.hpaned1);
			// Notebook tab
			this.tilesetsPage = new global::Gtk.Label ();
			this.tilesetsPage.Name = "tilesetsPage";
			this.tilesetsPage.LabelProp = global::Mono.Unix.Catalog.GetString ("Tilesets");
			this.notebook1.SetTabLabel (this.hpaned1, this.tilesetsPage);
			this.tilesetsPage.ShowAll ();
			w2.Add (this.notebook1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(w2 [this.notebook1]));
			w22.Position = 0;
			// Internal child Editor.DatabaseManagerWindow.ActionArea
			global::Gtk.HButtonBox w23 = this.ActionArea;
			w23.Name = "dialog1_ActionArea";
			w23.Spacing = 10;
			w23.BorderWidth = ((uint)(5));
			w23.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w24 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w23 [this.buttonCancel]));
			w24.Expand = false;
			w24.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w23 [this.buttonOk]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
		}
	}
}
