
// This file has been generated by the GUI designer. Do not modify.
namespace Editor
{
	public partial class TilesetEditorWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Editor.TilesetEditorWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Editor.TilesetEditorWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
