
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;
	
	private global::Gtk.Action FileAction;
	
	private global::Gtk.Action DatabaseAction;
	
	private global::Gtk.Action TilesetsAction;
	
	private global::Gtk.Action CharactersAction;
	
	private global::Gtk.Action AnimationsAction;
	
	private global::Gtk.Action MonstersAction;
	
	private global::Gtk.Action AttacksAction;
	
	private global::Gtk.Action EditAction;
	
	private global::Gtk.Action DrawAction;
	
	private global::Gtk.Action ScaleAction;
	
	private global::Gtk.Action ToolsAction;
	
	private global::Gtk.Action GameAction;
	
	private global::Gtk.VBox vbox1;
	
	private global::Gtk.MenuBar menubar2;
	
	private global::Gtk.Toolbar mainToolbar;
	
	private global::Gtk.HPaned hpaned1;
	
	private global::Gtk.VPaned vpaned4;
	
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	
	private global::Gtk.TreeView treeview1;
	
	private global::Gtk.ScrolledWindow scrolledwindow2;
	
	private global::Gtk.Statusbar statusbar1;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, null);
		this.DatabaseAction = new global::Gtk.Action ("DatabaseAction", global::Mono.Unix.Catalog.GetString ("Database"), null, null);
		this.DatabaseAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Database");
		w1.Add (this.DatabaseAction, null);
		this.TilesetsAction = new global::Gtk.Action ("TilesetsAction", global::Mono.Unix.Catalog.GetString ("Tilesets"), null, null);
		this.TilesetsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tilesets");
		w1.Add (this.TilesetsAction, null);
		this.CharactersAction = new global::Gtk.Action ("CharactersAction", global::Mono.Unix.Catalog.GetString ("Characters"), null, null);
		this.CharactersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Characters");
		w1.Add (this.CharactersAction, null);
		this.AnimationsAction = new global::Gtk.Action ("AnimationsAction", global::Mono.Unix.Catalog.GetString ("Animations"), null, null);
		this.AnimationsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Animations");
		w1.Add (this.AnimationsAction, null);
		this.MonstersAction = new global::Gtk.Action ("MonstersAction", global::Mono.Unix.Catalog.GetString ("Monsters"), null, null);
		this.MonstersAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Monsters");
		w1.Add (this.MonstersAction, null);
		this.AttacksAction = new global::Gtk.Action ("AttacksAction", global::Mono.Unix.Catalog.GetString ("Attacks"), null, null);
		this.AttacksAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Attacks");
		w1.Add (this.AttacksAction, null);
		this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
		this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
		w1.Add (this.EditAction, null);
		this.DrawAction = new global::Gtk.Action ("DrawAction", global::Mono.Unix.Catalog.GetString ("Draw"), null, null);
		this.DrawAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Draw");
		w1.Add (this.DrawAction, null);
		this.ScaleAction = new global::Gtk.Action ("ScaleAction", global::Mono.Unix.Catalog.GetString ("Scale"), null, null);
		this.ScaleAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Scale");
		w1.Add (this.ScaleAction, null);
		this.ToolsAction = new global::Gtk.Action ("ToolsAction", global::Mono.Unix.Catalog.GetString ("Tools"), null, null);
		this.ToolsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Tools");
		w1.Add (this.ToolsAction, null);
		this.GameAction = new global::Gtk.Action ("GameAction", global::Mono.Unix.Catalog.GetString ("Game"), null, null);
		this.GameAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Game");
		w1.Add (this.GameAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(1));
		this.DefaultWidth = 1280;
		this.DefaultHeight = 768;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar2'><menu name='FileAction' action='FileAction'/><menu name='EditAction' action='EditAction'/><menu name='DatabaseAction' action='DatabaseAction'><menuitem name='TilesetsAction' action='TilesetsAction'/><menuitem name='CharactersAction' action='CharactersAction'/><menuitem name='AnimationsAction' action='AnimationsAction'/><menuitem name='MonstersAction' action='MonstersAction'/><menuitem name='AttacksAction' action='AttacksAction'/></menu><menu name='DrawAction' action='DrawAction'/><menu name='ScaleAction' action='ScaleAction'/><menu name='ToolsAction' action='ToolsAction'/><menu name='GameAction' action='GameAction'/></menubar></ui>");
		this.menubar2 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar2")));
		this.menubar2.Name = "menubar2";
		this.vbox1.Add (this.menubar2);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar2]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='mainToolbar'/></ui>");
		this.mainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/mainToolbar")));
		this.mainToolbar.Name = "mainToolbar";
		this.mainToolbar.ShowArrow = false;
		this.mainToolbar.IconSize = ((global::Gtk.IconSize)(2));
		this.vbox1.Add (this.mainToolbar);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.mainToolbar]));
		w3.Position = 1;
		w3.Expand = false;
		w3.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.hpaned1 = new global::Gtk.HPaned ();
		this.hpaned1.CanFocus = true;
		this.hpaned1.Name = "hpaned1";
		this.hpaned1.Position = 120;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.vpaned4 = new global::Gtk.VPaned ();
		this.vpaned4.CanFocus = true;
		this.vpaned4.Name = "vpaned4";
		this.vpaned4.Position = 10;
		// Container child vpaned4.Gtk.Paned+PanedChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.treeview1 = new global::Gtk.TreeView ();
		this.treeview1.CanFocus = true;
		this.treeview1.Name = "treeview1";
		this.GtkScrolledWindow.Add (this.treeview1);
		this.vpaned4.Add (this.GtkScrolledWindow);
		this.hpaned1.Add (this.vpaned4);
		global::Gtk.Paned.PanedChild w6 = ((global::Gtk.Paned.PanedChild)(this.hpaned1 [this.vpaned4]));
		w6.Resize = false;
		// Container child hpaned1.Gtk.Paned+PanedChild
		this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow2.CanFocus = true;
		this.scrolledwindow2.Name = "scrolledwindow2";
		this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		this.hpaned1.Add (this.scrolledwindow2);
		this.vbox1.Add (this.hpaned1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned1]));
		w8.Position = 2;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusbar1 = new global::Gtk.Statusbar ();
		this.statusbar1.Name = "statusbar1";
		this.statusbar1.Spacing = 6;
		this.vbox1.Add (this.statusbar1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
		w9.Position = 3;
		w9.Expand = false;
		w9.Fill = false;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.TilesetsAction.Activated += new global::System.EventHandler (this.OnConfigureTilesetsAction);
	}
}
